name: soft-kit-be

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soft-kit
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 30
      interval: 5s
    restart: unless-stopped
    networks:
      - app-network

  auth-service:
    build:
      context: ./softKit-BE
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/softkit?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JAVA_OPTS: -Xms256m -Xmx384m
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network


