server:
  port: 8080

spring:
  application:
      name: softKit-BE

  datasource:
    url: jdbc:mysql://localhost:3306/softkit?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Use validate to Flyway manage schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        # validation configs
        javax.persistence.validation.mode: auto
        validator.apply_to_ddl: false
        validator.autoregister_listeners: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

# Custom CORS config
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600 # 1 hour cache

# Logging config
logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG