ALTER TABLE users
    CHANGE password password_hash VARCHAR(255) NOT NULL,
    CHANGE profile role ENUM('CUSTOMER','ADMIN') NOT NULL DEFAULT 'CUSTOMER',
    CHANGE phone phone_e164 VARCHAR(20) NULL,
    MODIFY created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE users
    ADD COLUMN status ENUM('PENDING','ACTIVE','DISABLED') NOT NULL DEFAULT 'PENDING' AFTER role,
    ADD COLUMN email_verified_at DATETIME(3) NULL AFTER email,
    ADD COLUMN failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0 AFTER phone_e164,
    ADD COLUMN locked_until DATETIME(3) NULL AFTER failed_login_attempts,
    ADD COLUMN last_login_at DATETIME(3) NULL AFTER locked_until;

ALTER TABLE users
    ADD UNIQUE KEY uq_users_email (email);
